/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthMetaRouteImport } from './routes/auth/meta'
import { Route as AuthMetaCallbackRouteImport } from './routes/auth/meta/callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthMetaRoute = AuthMetaRouteImport.update({
  id: '/auth/meta',
  path: '/auth/meta',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthMetaCallbackRoute = AuthMetaCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthMetaRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/meta': typeof AuthMetaRouteWithChildren
  '/auth/meta/callback': typeof AuthMetaCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/meta': typeof AuthMetaRouteWithChildren
  '/auth/meta/callback': typeof AuthMetaCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth/meta': typeof AuthMetaRouteWithChildren
  '/auth/meta/callback': typeof AuthMetaCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth/meta' | '/auth/meta/callback'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth/meta' | '/auth/meta/callback'
  id: '__root__' | '/' | '/auth/meta' | '/auth/meta/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthMetaRoute: typeof AuthMetaRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/meta': {
      id: '/auth/meta'
      path: '/auth/meta'
      fullPath: '/auth/meta'
      preLoaderRoute: typeof AuthMetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/meta/callback': {
      id: '/auth/meta/callback'
      path: '/callback'
      fullPath: '/auth/meta/callback'
      preLoaderRoute: typeof AuthMetaCallbackRouteImport
      parentRoute: typeof AuthMetaRoute
    }
  }
}

interface AuthMetaRouteChildren {
  AuthMetaCallbackRoute: typeof AuthMetaCallbackRoute
}

const AuthMetaRouteChildren: AuthMetaRouteChildren = {
  AuthMetaCallbackRoute: AuthMetaCallbackRoute,
}

const AuthMetaRouteWithChildren = AuthMetaRoute._addFileChildren(
  AuthMetaRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthMetaRoute: AuthMetaRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
